[2024-01-23T15:45:55.610+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: execute_python_files_dag.execute_python_file_3 manual__2024-01-23T15:45:34.217359+00:00 [queued]>
[2024-01-23T15:45:55.624+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: execute_python_files_dag.execute_python_file_3 manual__2024-01-23T15:45:34.217359+00:00 [queued]>
[2024-01-23T15:45:55.624+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-23T15:45:55.769+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): execute_python_file_3> on 2024-01-23 15:45:34.217359+00:00
[2024-01-23T15:45:55.774+0000] {standard_task_runner.py:60} INFO - Started process 218 to run task
[2024-01-23T15:45:55.778+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'execute_python_files_dag', 'execute_python_file_3', 'manual__2024-01-23T15:45:34.217359+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmpl6661bf_']
[2024-01-23T15:45:55.779+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask execute_python_file_3
[2024-01-23T15:45:55.986+0000] {task_command.py:423} INFO - Running <TaskInstance: execute_python_files_dag.execute_python_file_3 manual__2024-01-23T15:45:34.217359+00:00 [running]> on host b977193ffa62
[2024-01-23T15:45:56.279+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='execute_python_files_dag' AIRFLOW_CTX_TASK_ID='execute_python_file_3' AIRFLOW_CTX_EXECUTION_DATE='2024-01-23T15:45:34.217359+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-23T15:45:34.217359+00:00'
[2024-01-23T15:45:56.280+0000] {logging_mixin.py:188} INFO - Error executing file C:\Users\havet\Desktop\workflow_1\load.py: [Errno 2] No such file or directory: 'C:\\Users\\havet\\Desktop\\workflow_1\\load.py'
[2024-01-23T15:45:56.280+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-23T15:45:56.292+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=execute_python_files_dag, task_id=execute_python_file_3, execution_date=20240123T154534, start_date=20240123T154555, end_date=20240123T154556
[2024-01-23T15:45:56.514+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-23T15:45:56.537+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
